import {NextResponse} from 'next/server';
import {getDb} from '@/lib/mongodb';

const MAX_BYTES=900_000;
const norm=(v:unknown)=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');
function fingerprint(fields:any){return [fields?.district,fields?.taluk,fields?.village,fields?.survey,fields?.subdivision,fields?.owner,fields?.extentAcres].map(norm).join('|')}
function cleanCase(input:any){return{caseId:String(input?.caseId||`LG-${Date.now()}`).slice(0,80),createdAt:new Date(input?.createdAt||Date.now()),updatedAt:new Date(),decision:String(input?.decision||'').slice(0,80),status:String(input?.status||'PENDING').slice(0,40),mode:'production',result:input?.result||null,parcel:input?.parcel||null,assignedOfficer:String(input?.assignedOfficer||'PUBLIC INTAKE').slice(0,200),documents:Array.isArray(input?.documents)?input.documents.slice(0,12).map((d:any)=>({id:String(d?.id||'').slice(0,80),type:String(d?.type||'').slice(0,80),name:String(d?.name||'').slice(0,200),size:Number(d?.size||0),confidence:Number(d?.confidence||0),method:String(d?.method||'').slice(0,40),fields:d?.fields||{}})):[]}}

export async function GET(){try{const db=await getDb();const cases=await db.collection('cases').find({}, {projection:{_id:0}}).sort({createdAt:-1}).limit(200).toArray();return NextResponse.json({cases})}catch{return NextResponse.json({error:'Persistent storage unavailable.'},{status:503})}}

export async function POST(req:Request){try{const raw=await req.text();if(Buffer.byteLength(raw,'utf8')>MAX_BYTES)return NextResponse.json({error:'Case payload too large.'},{status:413});const item=cleanCase(JSON.parse(raw));if(!item.documents.length)return NextResponse.json({error:'At least one document is required.'},{status:400});const identity=item.documents.find((d:any)=>d.fields?.survey||d.fields?.owner)?.fields||{};const fp=fingerprint(identity);const db=await getDb();const cases=db.collection('cases');await cases.createIndex({caseId:1},{unique:true});await cases.createIndex({createdAt:-1});await cases.createIndex({fingerprint:1});const duplicate=fp?await cases.findOne({fingerprint:fp,caseId:{$ne:item.caseId}},{projection:{_id:0,caseId:1,status:1}}):null;item.assignedOfficer=item.assignedOfficer||'PUBLIC INTAKE';await cases.insertOne({...item,fingerprint:fp,duplicateCheck:duplicate?{isDuplicate:true,matchedCaseId:duplicate.caseId,matchedStatus:duplicate.status}:{isDuplicate:false}});return NextResponse.json({ok:true,caseId:item.caseId,duplicate:duplicate?{caseId:duplicate.caseId}:null})}catch(error:any){if(error?.code===11000)return NextResponse.json({error:'Case ID already exists. Please save again.'},{status:409});return NextResponse.json({error:'Could not save case.'},{status:500})}}
